### ISSUE TITLE
Add Sass support

### ISSUE THREAD

**Issue by wrightmartin** [jdrever/changethestory.eu#1]
Not sure the best way to do this in Eleventy as it's not built in, we could either

- Add a dependency to the project and have a build process, add css to `.gitignore`
- Use Sass compilation locally and commit css files to the repo

**Comment by jdrever** [comment]
I’m easy Martin – I don’t have a problem with a dependency being added.  As I’m sure you’ve found, there’s various ways (using or not using gulp).  I’m happy for you to find the approach you’re most comfortable with but could you let me know which way you’ve gone.

**Comment by wrightmartin** [comment]
I think for now let's go with the simplest option first until we have a good reason to add complexity.

Let's compile Sass locally and commit the SCSS and CSS files to the repo

If we then configure git to treat the compiled CSS as binary files we won't get into merge hell (https://stackoverflow.com/questions/11162267/how-do-i-make-git-treat-a-file-as-binary). I'll update this ticket and the README.md when I make the changes

**Comment by jdrever** [comment]
-- let's go with the simplest option first until we have a good reason to add complexity.
Yep usually the best way! 😊
