### ISSUE TITLE
Issue with header font on Turkish pages

### ISSUE THREAD

**Issue by jdrever** [jdrever/changethestory.eu#12]
Hi Martin,

Some issues with the header font on the Turkish pages, e.g. https://www.changethestory.eu/turkey/teacher-support/ - is there anything we can do about this?

Many thanks,

James.

**Comment by wrightmartin** [comment]
Yep - this is because the font doesn't support extended characters, in the short term I can remove it via CSS on the countries that need the extra characters, longer term we should stop them from downloading the font if they won't need it

**Comment by wrightmartin** [comment]
fixed in https://github.com/jdrever/changethestory.eu/pull/11/commits/b274a036881dc8dd073161fe344d69a828c18489

**Comment by jdrever** [comment]
Thanks for all the changes, Martin.  I’ve merged them into master, so we’re live with them.

Now discussing with Richard exactly how the project + celebration/stories site is intended to relate to each other.

Is there space for the return of the (slightly smaller?) space person above the Change the Story header?

James.
