### ISSUE TITLE
Content model for a story?

### ISSUE THREAD

**Issue by wrightmartin** [jdrever/changethestory.eu#3]
Just starting to think about the wireframes and the content model for Stories is an unanswered question. As a guess:

Metadata
- Title
- Description
- Thumbnail (for display on site)
- Tag(s)
- Category
- Creator(s)
  - (would creators also need a 'school' or 'organisation')
- Date created (for sorting)
- Country

Content
- Images
- Videos
- HTML text content

**Comment by jdrever** [comment]
Yes, plus country.
