### ISSUE TITLE
Apply design to current site

### ISSUE THREAD

**Issue by wrightmartin** [jdrever/changethestory.eu#4]
Here's a mockup of how we could do this in a fairly simple way, without drastically changing the site
![Desktop HD](https://user-images.githubusercontent.com/2292925/98038984-e4667b00-1e15-11eb-9e61-0ea95cd80138.png)

**Comment by jdrever** [comment]
Hi Martin, initial thoughts: that looks fine in terms of the project website delivery, but not sure from this how the site will look in celebration site mode?  Did you have any further thoughts about the logo (not it’s not included in the mockup)?  James.

**Comment by wrightmartin** [comment]
> that looks fine in terms of the project website delivery, but not sure from this how the site will look in celebration site mode

Working on that at the moment :) Will have some page wireframes to show soon

> Did you have any further thoughts about the logo (not it’s not included in the mockup)? 

I've started a redraw but I didn't want to get stuck on it for a long time and not progress anything else. It's in progress :)

**Comment by jdrever** [comment]
Great, thanks Martin!  Really appreciate the updates 😊

**Comment by wrightmartin** [comment]
Hi James,

Sorry I've been falling behind with this - combination of a mad last few weeks at the day job and then Christmas. The sort of good news is I'm now isolating for 10 days so have an abundance of time to make this my focus. 

I've been through the feedback and made a few changes to the design - aiming for softer and warmer generally, and more approachable in a 'youth friendly' way rather than a 'insurance broker firm' way. Let me know thoughts. Will start putting the basics into the front-end now

Martin

![Desktop HD](https://user-images.githubusercontent.com/2292925/103206383-a2c4ee80-48f3-11eb-917d-0f466dd17efd.png)

**Comment by jdrever** [comment]
Hey Martin,

Great to hear you’re back on this, but…

--I'm now isolating for 10 days
Are you/everyone OK??

James.

**Comment by wrightmartin** [comment]
> Are you/everyone OK??

Everyone is fine, brother had a positive test result after Christmas and we spent some time with him in the morning. We haven't been officially ordered to isolate via track and trace but would rather be on the safe side. Everyone thankfully is healthy and symptomless at the moment
