### ISSUE TITLE
Wireframes for key pages

### ISSUE THREAD

**Issue by wrightmartin** [jdrever/changethestory.eu#5]
# Home
There's a lot of room for flexibility on the home page, for example do you want any editorial content, or call outs for teachers or resources or anything?

![Home](https://user-images.githubusercontent.com/2292925/98785391-706b3a80-23f4-11eb-96e8-b33ea48247f9.png)

# Browse
Pretty simple layout, we'll use some way of showing if a story is mostly video, or text or photos with the thumbnail, and surface a little meta information to assist when browsing. Also using filters might make this easier to use when the amount of stories grows
![Browse stories](https://user-images.githubusercontent.com/2292925/98785409-76f9b200-23f4-11eb-9a61-070a37a8b6aa.png)

# Story page
I've tried to keep this flexible. The top section is all meta-information (the squares will be icons), next to the contents of the 'description' field. After that I'm expecting this to be HTML via markdown of the story itself.

![Story page](https://user-images.githubusercontent.com/2292925/98785419-78c37580-23f4-11eb-8318-7bfc46b7466e.png)

**Comment by jdrever** [comment]
Hi Martin,

Thanks for this.  I think we’re generally on the right track.

A few comments:

From Richard:  “It looks very clean and legible which are both good. I would, however, associate the design with an insurance company wishing to demonstrate a professional and efficient image. For me it lacks warmth and an invitation to explore; too angular and cold. The headings along the top, taken from the existing site, are not necessary to be featured so prominently. The key audience are pupils; the teachers part needs to be a whole separate area accessible from the celebration homepage.”

We realise that the site is designed to humbly highlight the stories, but it’s not quite clear to me that, e.g. the thumbnails of stories on the home page will look that compelling in themselves – we may not always have great images for them.  I think a little more vibrancy in the basic design would be good.

We also realise that the home page is effectively just a placeholder at this stage, but comments from Richard again quite helpful: “the image of the kids in a field dominates and set the tone for the whole thing. The angularity of that image and how it frames the title does not work for me. I feel there needs to be something much more playful and free flowing which will offset the regular patterns of boxes elsewhere.”

Richard has also clarified that the celebration site needs a different set of top menu items to the project site for teachers (with the teachers link below going to the current site)

  *   Take action – link to actions young people are taking; stories from influencers.
  *   Find out – link to a careful selection of other projects and sources of information.
  *   Share – link to suggestions of how to share and influence others.
  *   Teachers – link to assessment/teacher support/learning resources/project documents.
  *   About – about.

If you could incorporate these into the celebration site designs that would be great.  I can set up some pages in 11ty now I know what we need.

Plus we’ll need a country selector for the celebration site

We’ll want the ability for pupils/others to comments on stories on each story page

The partners are asking about using logo/font etc outside of the website – be great if you could share the reworked logo & font choices etc once they are confirmed/ahead of the site going live – that has become more of priority than it was.  If you’re able to share some idea of when that will be possible, that would be very helpful.

I’m wondering how best to share the design with partners and potentially teachers/pupils/others involved in the project (which we do need to do before we get much further along) – at the moment, I think they’d have to use their imaginations possibly a little more than is safe – e.g. the design without the stories inevitably looks a bit low key.  What are your thoughts?

Hope that’s helpful, shout with whatever you need, and hope you have a brilliant weekend.  Feels like a long week here, but have got a lot done!

James.

**Comment by wrightmartin** [comment]
Just to clarify - these are wireframes, just meant to show the structure and content that will be on each page, not design, so hopefully the insurancey feel will disappear. Made some great progress with the logo last week, will finish up and show before the end of the week

**Comment by jdrever** [comment]
Understood, yes did emphasise that to Richard but thought his comments were helpful as we move towards the design.  Will look forward to the logo, have a great week  😊
