### ISSUE TITLE
Can we add Bootstrap front-end framework

### ISSUE THREAD

**Issue by wrightmartin** [jdrever/changethestory.eu#7]
It's not needed for the initial version of the site but will be handy to have something tested and well understood for the front-end when we add stories to the display layer

I understand this is an extra dependency but will give us a layout framework we can reuse rather than invent our own

**Comment by jdrever** [comment]
So I’ll rely on your judgement – but just want to check quickly: is there a more lightweight alternative?

**Comment by wrightmartin** [comment]
We can keep it small if we only include what we'll require (which I think is quite small all in)

https://getbootstrap.com/docs/5.0/customize/sass/#importing

**Comment by jdrever** [comment]
OK, go for it
